/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32g031xx.h"

#define LED_PIN     6   // PC6
#define LED_PORT    GPIOC

void delay(volatile uint32_t count)
{
    while(count--) { __NOP(); }
}

int main(void)
{
    /* Enable GPIOC clock */
    RCC->IOPENR |= RCC_IOPENR_GPIOCEN;

    /* Configure PC6 as output */
    LED_PORT->MODER &= ~(0x3 << (LED_PIN * 2));  // clear mode
    LED_PORT->MODER |=  (0x1 << (LED_PIN * 2));  // set output

    /* Optional: output type push-pull (default) */
    LED_PORT->OTYPER &= ~(1 << LED_PIN);

    /* Optional: medium speed */
    LED_PORT->OSPEEDR &= ~(0x3 << (LED_PIN * 2));
    LED_PORT->OSPEEDR |=  (0x1 << (LED_PIN * 2));

    /* Optional: no pull-up/pull-down */
    LED_PORT->PUPDR &= ~(0x3 << (LED_PIN * 2));

    while(1)
    {
        /* Toggle LED */
        LED_PORT->ODR ^= (1 << LED_PIN);

        /* Simple delay */
        delay(1000000);
    }
}

